### PR TITLE
Migrate to namespace format and apply new conventions

### PR DESCRIPTION
**Pull request by justinmayer**
Following up on: https://github.com/getpelican/pelican-plugins/issues/1290

### CODE REVIEW

**Comment by justinmayer** [comment]
@kdeldycke: I realized I forgot to test the plugin and make sure it actually works. 🤦  Would you mind giving the version in this branch a try and ensuring it functions properly?

**Comment by kdeldycke** [comment]
Just tested the plugin locally, and it works perfectly!

LGTM, let's merge this PR and release the plugin on PyPi! 🎉

**Comment by justinmayer** [comment]
Many thanks for testing this, Kevin! 🥇

**Comment by kdeldycke** [comment]
Thanks again @justinmayer !

**Pull request merged**
